### ISSUE TITLE
create radio buttons for player choices in index.html

### ISSUE THREAD

**Issue by GingerKiwi** [GingerKiwi/alice-game#1]
The text for the radio buttons can be found on lines 54 to 59 of the .py file.

**Comment by sivasuriyankumarasamy** [comment]
@GingerKiwi, can you assign this to me?

**Comment by GingerKiwi** [comment]
Sure. Would you please have a quick read of CONTRIBUTING.md
and introduce yourself in https://github.com/GingerKiwi/alice-game/discussions.

**Comment by sivasuriyankumarasamy** [comment]
Hi @GingerKiwi ,
Raised pr for this issue.
https://github.com/GingerKiwi/alice-game/pull/9

Please review. 
If you merge the changes please add hacktoberfest-accepted label in the pr
