### ISSUE TITLE
Create about.html with boilerplate

### ISSUE THREAD

**Issue by GingerKiwi** [GingerKiwi/alice-game#12]
- [ ] create about.html file
- [ ] copy and paste the boilerplate from line 1 to line 21 in index.html 
- [ ] Add a h1 for "About This Project"
- [ ] Add blank <main></main>
- [ ] Copy and paste the footer code from index.html

**Comment by Mirza-Hassan** [comment]
@GingerKiwi can you please assign me?

**Comment by GingerKiwi** [comment]
Done!
I'm in EDT (Toronto, Canada). I'll be quickly checking tomorrow morning (about 12-14hrs) and early evening. So this should count for hacktoberfest!

**Comment by Mirza-Hassan** [comment]
@GingerKiwi I've raised a PR https://github.com/GingerKiwi/alice-game/pull/14 . Please review it. Thanks
