### ISSUE TITLE
Introduce Yourself

### ISSUE THREAD

**Issue by wvinson43** [GingerKiwi/alice-game#16]
### Discussed in https://github.com/GingerKiwi/alice-game/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **GingerKiwi** October 29, 2022</sup>
This is a project for new devs wanting to learn open source web development and version control (github) with others. The first step is to introduce yourself in the discussions tab. Please answer the following quick questions.

1. What is your real first name and Github profile link?
2. Where in the world are you (country and time zone)?
3. Where are you in your learning journey? -> Just learning html, know html and css, just started learning javascript, comforatble with more advanced javascript such as promises, api, etc.?
4. How are you learning? -> Self taught, bootcamp, computer science courses
5. What would you like to work on in this repo</div>

**Comment by wvinson43** [comment]
1. Wes-https://github.com/wvinson43
2. USA-Central
3. I am on the edge of finishing the Front End Developer Path w Scrimba-so Junior Developer-Focused on React-Front-End. Some full-stack experience as well.
4. Self-taught and Scrimba Camp.
5. I will work on whatever you need that I am able to do.

**Comment by SKVKPandey** [comment]
Hey,

1. My name is Shashank Kashyap Vijay Kumar Pandey and my GitHub profile link is: https://github.com/SKVKPandey
2. South Delhi, Delhi, India.
3. Currently, I work as a freelancer web developer (full-stack) and I love contributing to open-source projects.
4. I am a 2nd Year electronics student and I have learned to code by practicing myself and making projects.
5. I'd like to contribute to the CSS part of the front end.

**Comment by GingerKiwi** [comment]
Please use the discussion tab for this. 
Thanks!
