### ISSUE TITLE
add nav links in footer on about.html 

### ISSUE THREAD

**Issue by GingerKiwi** [GingerKiwi/alice-game#21]
Starting on line 24 of about.html:

- [ ] create an unordered list
- [ ] add a link to index.html as a li
- [ ] add a link to about.html as a li
- [ ] add a link to this repo (https://github.com/GingerKiwi/alice-game) as an li

**Comment by srijoy-paul** [comment]
Hey @GingerKiwi can you assign me this task?

**Comment by nishtha53** [comment]
@GingerKiwi can i work on this issue?

**Comment by Vishu-uut** [comment]
@GingerKiwi I would love to fix this task if you are willing to assign it to me
