### ISSUE TITLE
create dark colour scheme and add css color variables to styles.css

### ISSUE THREAD

**Issue by GingerKiwi** [GingerKiwi/alice-game#6]
This is a basic clean three colour design to get the app up and running.
Colours should be in hsla format. It would be helpful to have the hex codes for the colours added as comments to the styles.css file.

**Comment by SKVKPandey** [comment]
Can you please assign this to me?

**Comment by SKVKPandey** [comment]
@GingerKiwi Can you please assign this to me?

**Comment by GingerKiwi** [comment]
Hi
Thanks for asking to contribute! 

Would you please introduce yourself in the discussion thread here: https://github.com/GingerKiwi/alice-game/discussions.
This repo is about learning socially. :-)

This is an issue I'm going to do myself, but there will be a related easy css one right when I'm done.
Kindly,
Liz

**Comment by SKVKPandey** [comment]
Hey,
I have introduced myself in the repo.
